### ISSUE TITLE
Why the score function use 'percent' as sigma?

### ISSUE THREAD

**Issue by nxyczz** [zabir-nabil/osic-pulmonary-fibrosis-progression#1]
def score_avg(p, a): # patient id, predicted a
    percent_true = train.Percent.values[train.Patient == p]
    fvc_true = train.FVC.values[train.Patient == p]
    weeks_true = train.Weeks.values[train.Patient == p]
    fvc = a * (weeks_true - weeks_true[0]) + fvc_true[0]
    percent = percent_true[0] - a * abs(weeks_true - weeks_true[0])
    return score(fvc_true, fvc, percent)

The last sentence use 'percent' as confidence, i dont understand. Who can teach me?

**Comment by mahdie-dolatabadi** [comment]
This is also my question? How percent can show the uncertainty or sigma?

**Comment by zabir-nabil** [comment]
It's been a while I worked on this but you can get some insights from 2.1. FVC formulation. We approximate the future FVC with a linear prior instead of predicting the FVC values at each temporal points. The evaluation metric is discussed in section 4. Sigma is mainly used for clipping. Since we don't predict the FVC at each temporal points, we measure variability σ using the linear slope as a proxy (abs (week vector - baseline week) scaled by slope and then we measure the change relative to baseline which gives us the variability), if it's less than 70 (high confidence, low variability), it's clipped anyway.
